dashboard/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('settings/<int:pk>/update', views.SiteSettingsUpdateView.as_view(), name='site-settings'),
    path('users/', views.UserListView.as_view(), name='all-users'),
    path('user/account/create/', views.UserAccountCreateView.as_view(), name='account_create'),
    path('myaccount/<int:pk>/update/', views.UserAccountUpdateView.as_view(), name='account_update'),

    
    path('user/profile/<int:pk>/update/', views.UserProfileUpdateView.as_view(), name='profile_update'),
    path('user/profile/create', views.UserProfileCreateView.as_view(), name='profile_create'),
    path('user/<int:pk>/delete/', views.UserDeleteView.as_view(), name='user_delete'),
#    path('change-password/', auth_views.PasswordChangeView.as_view()),

    
    path('products/', views.ProductsListView.as_view(), name='all-products'),
    path('product/detail/<uuid:pk>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('product/item/create', views.ProductCreateView.as_view(), name='product_item_create'),
    path('product/summary/<uuid:pk>/update', views.ItemSummaryUpdateView.as_view(), name='product_item_update'),
    
    path('product/price/create', views.PriceCreateView.as_view(), name='product_price_create'),
    path('product/price/<uuid:pk>/update', views.PriceUpdateView.as_view(), name='product_price_update'),
    
    path('product/stock/create', views.StockCreateView.as_view(), name='product_stock_create'),
    path('product/stock/<uuid:pk>/update', views.StockUpdateView.as_view(), name='product_stock_update'),
    
    path('product/images/create', views.ProductImagesCreateView.as_view(), name='product_images_create'),

    path('product/images/<uuid:pk>/update', views.ProductImagesUpdateView.as_view(), name='product_images_update'),
    
    
]

eshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('', RedirectView.as_view(url='products/', permanent=True)),
    path('dashboard/', include('dashboard.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

dashboard/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class UserProfile(models.Model):
    account_info = models.ForeignKey(User, on_delete=models.CASCADE, help_text="website login account, (not deals with accountant informations).")
    phone = models.CharField(max_length=13, help_text="Phone Number")
    nrc = models.CharField('NRC Number', max_length=18, null=True, blank=True)
    address = models.TextField(help_text="Enter Full Address.")
    salary = models.IntegerField()

    def __str__(self):

       return f"{self.account_info}"

dashboard/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import decorators
from django.urls import reverse_lazy, reverse

# Create your views here.
@decorators.login_required
def index(request):
    return render(request, 'dashboard/index.html')


from django.views.generic.edit import FormView, UpdateView, CreateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from siteinfo.models import SiteSettings

class SiteSettingsUpdateView(LoginRequiredMixin, UpdateView):

    model = SiteSettings
    fields = '__all__'
    template_name = 'dashboard/sitesettings_update_form.html'



from django.views.generic import ListView, DetailView
from django.contrib.auth.models import User

class UserListView(LoginRequiredMixin, ListView):
    model = User
    context_object_name = 'users'
    template_name = 'dashboard/all_user_list.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['extraProfile'] = UserProfile.objects.all()

        return context
    


class UserAccountCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'is_superuser'
    model = User
    fields = ['first_name', 'last_name', 'username', 'email', 'password', 'user_permissions', 'is_superuser']
    template_name = 'auth/user_form.html'
    success_url = reverse_lazy('dashboard:profile_create')

    

class UserAccountUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    fields = ['first_name', 'last_name', 'username', 'email']
    template_name = 'dashboard/user_form.html'

    

from dashboard.models import UserProfile
class UserProfileCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'is_superser'
    model = UserProfile
    fields = '__all__'
    success_url = reverse_lazy('dashboard:all-users')
    

    
class UserProfileUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = 'is_superuser'
    model = UserProfile
    #fields = '__all__'
    fields = ['nrc', 'phone', 'address', 'salary']
    #fields = ['username', 'first_name', 'last_name', 'email']
    success_url = reverse_lazy('dashboard:all-users')



    

class UserDeleteView(PermissionRequiredMixin, DeleteView):
    model = User



from products.models import Product, Stock, ProductImages, Price
class ProductsListView(LoginRequiredMixin, ListView):
    model = Product
    context_object_name = 'products'
    template_name = 'products/all_product_list.html'

    def get_queryset(self):
        return Product.objects.all()


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['prices'] = Price.objects.all()
        context['stocks'] = Stock.objects.all()
        context['Pimages'] = ProductImages.objects.all()
        
        return context


    

class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    context_object_name = 'product'
    template_name = 'products/product_detail.html'

  
    
class ProductCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'is_superuser'
    model = Product
    fields = '__all__'
    success_url = reverse_lazy('dashboard:product_stock_create')


class ItemSummaryUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = 'is_superuser'
    model = Product
    fields = '__all__'

    def get_success_url(self, **kwargs):         
        return reverse_lazy("dashboard:product-detail", args=(self.kwargs['pk'],))

    

    
class PriceCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'is_superuser'
    model = Price
    fields = '__all__'
    success_url = reverse_lazy('dashboard:product_images_create')


class PriceUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = 'is_superuser'
    model = Price
    fields = ['low_price', 'normal_price', 'tenth_price', 'base_price']

    def get_success_url(self, **kwargs):         
        return reverse_lazy("dashboard:product-detail", args=(self.kwargs['pk'],))

    
    

class StockCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'is_superuser'
    model = Stock
    fields = '__all__'
    success_url = reverse_lazy('dashboard:product_price_create')


class StockUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = 'is_superuser'
    model = Stock
    fields = ['stock']

    def get_success_url(self, **kwargs):         
        return reverse_lazy("dashboard:product-detail", args=(self.kwargs['pk'],))




class ProductImagesCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'is_superuser'
    model = ProductImages
    fields = '__all__'
    success_url = reverse_lazy('dashboard:all-products')



    
class ProductImagesUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = 'is_superuser'
    model = ProductImages
    fields = ['featured_image', 'image1', 'image2', 'image3']

    def get_success_url(self, **kwargs):         
        return reverse_lazy("dashboard:product-detail", args=(self.kwargs['pk'],))

    

dashboard/templates/dashboard/admin-dash/main.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!--<link rel="stylesheet" href="{% static 'css/mdb.min.css' %}">-->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block title %}
    <title>Admin Dashboard</title>
    {% endblock %}
  </head>
  <body style="height:100%;">
    <div class="container-fluid" >
      <div class="row">
	<div class="col bg-info text-light ">
	  {% include './sidebar.html' %}
	</div>

	<div class="col-12 col-sm-10">
	  
	  {% block content %}
    
	  <h1>Hello, admin!</h1>
	  {% endblock %}
	</div>
      </div>
    </div>
    

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'js/jquery.slim.min.js' %}"></script>
    <script src="{% static 'js/popover.js' %}"> </script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>


    <script src="{% static 'js/feather.js' %}"></script>

    <!--<script src="{% static 'js/mdb.min.js' %}"></script>-->
    
    <script>



      feather.replace({'width':'18','height':'18'})


    </script>
    {% block footer %}
    {% endblock %}
  </body>
</html>

dashboard/templates/dashboard/admin-dash/sidebar.html
<div class="" style="min-height:720px;">
  <div class="pb-2 pt-3 text-center btn-link  text-light align-items-center">
    <i data-feather="user"></i> <strong class="text-monospace">{{user.username}} </strong>
    </div>
  
  <div class="p-3 pt-0 pb-0 mb-3ext-light">
    <div class="list-group list-group-flush">
      <a href="" class="list-group-item list-group-action bg-info text-light">
	<i data-feather="command"></i> Dashboard
      </a>
      <a href="#" class="list-group-item list-group-item-action bg-info text-light">
	<i data-feather="file-text"></i> Sales</a>
      <a href="{% url 'dashboard:all-products' %}" class="list-group-item list-group-item-action bg-info text-light">
	<i data-feather="box"></i> Products</a>
      <a href="#" class="list-group-item list-group-item-action bg-info text-light">
	<i data-feather="check-circle"></i> Category</a>
      <a href="#" class="list-group-item list-group-item-action bg-info text-light">
	<i data-feather="shopping-bag"></i> Warehouse</a>
      {% if user.is_staff %}
      <a href="{% url 'dashboard:all-users' %}" class="list-group-item list-group-item-action bg-info text-light">
	<i data-feather="users"></i> Users Profile </a>
      {% endif %}
      <a href="{% url 'dashboard:account_update' user.id  %}" class="list-group-item list-group-item-action bg-info text-light">
	<i data-feather="user-check"></i> My Account </a>
      <a href="{% url 'dashboard:site-settings' 1 %}" class="list-group-item list-group-item-action bg-info text-light">
	<i data-feather="settings"></i> Site Settings </a>
      <a href="{% url 'logout'  %}" class="list-group-item list-group-item-action bg-info text-light">
	<i data-feather="log-out"></i> Logout </a>
      </div>

  </div>
  
</div>