dashboard/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('settings/<int:pk>/update', views.SiteSettingsUpdateView.as_view(), name='site-settings'),
    path('users/', views.UserListView.as_view(), name='all-users'),
    path('user/account/create/', views.UserAccountCreateView.as_view(), name='account_create'),
    path('myaccount/<int:pk>/update/', views.UserAccountUpdateView.as_view(), name='account_update'),

    
    path('user/profile/<int:pk>/update/', views.UserProfileUpdateView.as_view(), name='profile_update'),
    path('user/profile/create', views.UserProfileCreateView.as_view(), name='profile_create'),
    path('user/<int:pk>/delete/', views.UserDeleteView.as_view(), name='user_delete'),
#    path('change-password/', auth_views.PasswordChangeView.as_view()),

    
    path('products/', views.ProductsListView.as_view(), name='all-products'),
    path('product/detail/<uuid:pk>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('product/item/create', views.ProductCreateView.as_view(), name='product_item_create'),
    path('product/summary/<uuid:pk>/update', views.ItemSummaryUpdateView.as_view(), name='product_item_update'),
    
    path('product/price/create', views.PriceCreateView.as_view(), name='product_price_create'),
    path('product/price/<uuid:pk>/update', views.PriceUpdateView.as_view(), name='product_price_update'),
    
    path('product/stock/create', views.StockCreateView.as_view(), name='product_stock_create'),
    path('product/stock/<uuid:pk>/update', views.StockUpdateView.as_view(), name='product_stock_update'),
    
    path('product/images/create', views.ProductImagesCreateView.as_view(), name='product_images_create'),

    path('product/images/<uuid:pk>/update', views.ProductImagesUpdateView.as_view(), name='product_images_update'),
    
    
]

eshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('', RedirectView.as_view(url='products/', permanent=True)),
    path('dashboard/', include('dashboard.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

dashboard/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class UserProfile(models.Model):
    account_info = models.ForeignKey(User, on_delete=models.CASCADE, help_text="website login account, (not deals with accountant informations).")
    phone = models.CharField(max_length=13, help_text="Phone Number")
    nrc = models.CharField('NRC Number', max_length=18, null=True, blank=True)
    address = models.TextField(help_text="Enter Full Address.")
    salary = models.IntegerField()

    def __str__(self):

       return f"{self.account_info}"

dashboard/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import decorators
from django.urls import reverse_lazy, reverse

# Create your views here.
@decorators.login_required
def index(request):
    return render(request, 'dashboard/index.html')


from django.views.generic.edit import FormView, UpdateView, CreateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from siteinfo.models import SiteSettings

class SiteSettingsUpdateView(LoginRequiredMixin, UpdateView):

    model = SiteSettings
    fields = '__all__'
    template_name = 'dashboard/sitesettings_update_form.html'



from django.views.generic import ListView, DetailView
from django.contrib.auth.models import User

class UserListView(LoginRequiredMixin, ListView):
    model = User
    context_object_name = 'users'
    template_name = 'dashboard/all_user_list.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['extraProfile'] = UserProfile.objects.all()

        return context
    


class UserAccountCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'is_superuser'
    model = User
    fields = ['first_name', 'last_name', 'username', 'email', 'password', 'user_permissions', 'is_superuser']
    template_name = 'auth/user_form.html'
    success_url = reverse_lazy('dashboard:profile_create')

    

class UserAccountUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    fields = ['first_name', 'last_name', 'username', 'email']
    template_name = 'dashboard/user_form.html'

    

from dashboard.models import UserProfile
class UserProfileCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'is_superser'
    model = UserProfile
    fields = '__all__'
    success_url = reverse_lazy('dashboard:all-users')
    

    
class UserProfileUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = 'is_superuser'
    model = UserProfile
    #fields = '__all__'
    fields = ['nrc', 'phone', 'address', 'salary']
    #fields = ['username', 'first_name', 'last_name', 'email']
    success_url = reverse_lazy('dashboard:all-users')



    

class UserDeleteView(PermissionRequiredMixin, DeleteView):
    model = User



from products.models import Product, Stock, ProductImages, Price
class ProductsListView(LoginRequiredMixin, ListView):
    model = Product
    context_object_name = 'products'
    template_name = 'products/all_product_list.html'

    def get_queryset(self):
        return Product.objects.all()


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['prices'] = Price.objects.all()
        context['stocks'] = Stock.objects.all()
        context['Pimages'] = ProductImages.objects.all()
        
        return context


    

class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    context_object_name = 'product'
    template_name = 'products/product_detail.html'

  
    
class ProductCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'is_superuser'
    model = Product
    fields = '__all__'
    success_url = reverse_lazy('dashboard:product_stock_create')


class ItemSummaryUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = 'is_superuser'
    model = Product
    fields = '__all__'

    def get_success_url(self, **kwargs):         
        return reverse_lazy("dashboard:product-detail", args=(self.kwargs['pk'],))

    

    
class PriceCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'is_superuser'
    model = Price
    fields = '__all__'
    success_url = reverse_lazy('dashboard:product_images_create')


class PriceUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = 'is_superuser'
    model = Price
    fields = ['low_price', 'normal_price', 'tenth_price', 'base_price']

    def get_success_url(self, **kwargs):         
        return reverse_lazy("dashboard:product-detail", args=(self.kwargs['pk'],))

    
    

class StockCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'is_superuser'
    model = Stock
    fields = '__all__'
    success_url = reverse_lazy('dashboard:product_price_create')


class StockUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = 'is_superuser'
    model = Stock
    fields = ['stock']

    def get_success_url(self, **kwargs):         
        return reverse_lazy("dashboard:product-detail", args=(self.kwargs['pk'],))




class ProductImagesCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'is_superuser'
    model = ProductImages
    fields = '__all__'
    success_url = reverse_lazy('dashboard:all-products')



    
class ProductImagesUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = 'is_superuser'
    model = ProductImages
    fields = ['featured_image', 'image1', 'image2', 'image3']

    def get_success_url(self, **kwargs):         
        return reverse_lazy("dashboard:product-detail", args=(self.kwargs['pk'],))

    

dashboard/templates/dashboard/all_user_list.html
{% extends './admin-dash/main.html' %}

{% block content %}

<div class="mt-3 ml-2 mr-2 mb-5">
  <strong class="text-monospace " style="font-size:18px;" > <u>User Accounts Panel</u> </strong>
  <a href="{% url 'dashboard:account_create' %}" class="d-inline-flex align-items-center btn btn-md btn-light float-right "> <i data-feather="user-plus"></i> &nbsp;Add Account </a>
  
</div>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">User Name</th>
      <th scope="col">Status</th>
      <th scope="col">Phone</th>
      <th scope="col">Super User</th>
      <th scope="col">Last Login </th>
    </tr>
  </thead>
  <tbody>
    {% for staff in extraProfile %}
    <tr >
      <th scope="row">{{forloop.counter}}</th>
      <td><a href="{% url 'dashboard:profile_update' staff.id %}">{{ staff.account_info }}</a></td>
      <td> </td>
      <td>{{staff.phone}}</td>
      <td>{% if staff.account_info.is_superuser %}
	 <i data-feather="check-circle"></i> 
	{% else %}
	  <i data-feather="x-circle"></i> 
	{% endif %}</td>
      <td> {{ staff.account_info.last_login }} </td>
    </tr>
    
    {% endfor %}

  </tbody>
  </table>
    
{% endblock %}

dashboard/templates/dashboard/index.html
{% extends './admin-dash/main.html' %}

{% block content %}
<div class="jumbotron" style="height:1200px;">
  <h3> Admin Dashboard </h3>
</div>

{% endblock %}

dashboard/templates/dashboard/setting.html
{% extends 'admin-dash/main.html' %}

{% block content %}

Site Settings

{% endblock %}

dashboard/templates/dashboard/sitesettings_update_form.html
{% extends './admin-dash/main.html' %}

{% block content %}
<div class="site-settings pt-3 pb-3">
<form method="post" action="" class="m-auto mt-3">{% csrf_token %}
  <h5 class="text-center text-monospace"> Site Settings </h5>
  <hr class="my-4">
    {{ form.as_p }}
    <input type="submit" class="btn btn-primary btn-md float-right" value="Update">
</form>
</div>

{% endblock %}

dashboard/templates/dashboard/user_form.html
{% extends 'dashboard/admin-dash/main.html' %}

{% block content %}
<div class="row justify-content-md-center">
  <div class="col-auto mt-5">
    <h5 class="text-center text-monospace"> Account Settings </h5>
    <hr class="my-4">
<form action="" method="post">
  {% csrf_token %}
  {{form.as_p}}
  <small><a href="{% url 'password_change' %}"> Change Password ? </a> </small> <br>
  <input class="btn btn-md btn-success float-right"  type="submit" value="Update">
</form>
</div>

{% endblock %}

dashboard/templates/dashboard/userprofile_form.html
{% extends 'dashboard/admin-dash/main.html'%}

{% block content %}
<div class="row justify-content-md-center">
  <div class="col-auto mt-5">
    <h5 class="text-center text-monospace"> Account Profile </h5>
    <hr class="my-4">
<form action="" method="post">
  {% csrf_token %}
  {{form.as_p}}
  <input class="btn btn-md btn-success"  type="submit" value="Update">
</form>
</div>

{% endblock %}