dashboard/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('settings/<int:pk>/update', views.SiteSettingsUpdateView.as_view(), name='site-settings'),
    path('users/', views.UserListView.as_view(), name='all-users'),
    path('user/account/create/', views.UserAccountCreateView.as_view(), name='account_create'),
    path('myaccount/<int:pk>/update/', views.UserAccountUpdateView.as_view(), name='account_update'),

    
    path('user/profile/<int:pk>/update/', views.UserProfileUpdateView.as_view(), name='profile_update'),
    path('user/profile/create', views.UserProfileCreateView.as_view(), name='profile_create'),
    path('user/<int:pk>/delete/', views.UserDeleteView.as_view(), name='user_delete'),
#    path('change-password/', auth_views.PasswordChangeView.as_view()),

    
    path('products/', views.ProductsListView.as_view(), name='all-products'),
    path('product/detail/<uuid:pk>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('product/item/create', views.ProductCreateView.as_view(), name='product_item_create'),
    path('product/summary/<uuid:pk>/update', views.ItemSummaryUpdateView.as_view(), name='product_item_update'),
    
    path('product/price/create', views.PriceCreateView.as_view(), name='product_price_create'),
    path('product/price/<uuid:pk>/update', views.PriceUpdateView.as_view(), name='product_price_update'),
    
    path('product/stock/create', views.StockCreateView.as_view(), name='product_stock_create'),
    path('product/stock/<uuid:pk>/update', views.StockUpdateView.as_view(), name='product_stock_update'),
    
    path('product/images/create', views.ProductImagesCreateView.as_view(), name='product_images_create'),

    path('product/images/<uuid:pk>/update', views.ProductImagesUpdateView.as_view(), name='product_images_update'),
    
    
]

eshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('', RedirectView.as_view(url='products/', permanent=True)),
    path('dashboard/', include('dashboard.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

products/urls.py
from django.urls import path, include
from . import views

app_name = 'products'

urlpatterns = [
    path('', views.index, name='index'),
]

products/models.py
import uuid
from django.db import models
from datetime import datetime as now_time
from django.urls import reverse_lazy, reverse


class MainCategory(models.Model):
    name = models.CharField(max_length=100, help_text="Category Name eg(TolyMoly).")
    info = models.TextField()
    
    def __str__(self):
        return self.name


    
class SubCategory(models.Model):
    name = models.CharField(max_length=100, help_text="Category Name eg(TolyMoly).")
    info = models.TextField()
    #main_category = models.ForeignKey('MainCategory', on_delete=models.SET_NULL, null=True)


    def __str__(self):
        return self.name

    

class Warehouse(models.Model):
    name = models.CharField('Warehouse Name', max_length=100)
    address = models.TextField(help_text="Enter WareHouse Address")

    
    def __str__(self):
        return self.name




class Product(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    model_number = models.CharField(max_length=100)
    name = models.CharField("Title",
                            max_length=200,
                            help_text="Enter Product Item Name")

    #images = models.ForeignKey('ProductImages', on_delete=models.SET_NULL, null=True)
    
    dimension = models.TextField(blank=True, null=True, help_text="eg.  1mm x 3mm x 10mm")
    summary = models.TextField(help_text="Enter Usage or Guideline")

    unit_choices = (
        ('co', 'Count'),
        ('ft', 'Feet'),
        ('kg', 'Kilogram'),
        ('lb', 'Pound'),
        ('tk', 'Tical'),
    )
    basic_unit = models.CharField(max_length=2,
                                  choices=unit_choices,
                                  default='co',
                                  help_text="Choice Unit")

    category1 = models.ManyToManyField(MainCategory)
    category2 = models.ManyToManyField(SubCategory)


    #stocks = models.ForeignKey('Stock', on_delete=models.CASCADE)
    #prices = models.ForeignKey('Price', on_delete=models.CASCADE, null=True, blank=True)
    

    limited = models.BooleanField(help_text="Mark if your product is limited")
    active_for_sale = models.BooleanField('Can Sale',default=True, help_text="if not available, Remove mark!")

    warehouse = models.ForeignKey('Warehouse', on_delete=models.SET_NULL, null=True)


    def __str__(self):
        return str(self.model_number)


    def get_absolute_url(self):
        return reverse('dashboard:product-detail', args=[str(self.id)])



class ProductImages(models.Model):
    product_id = models.OneToOneField(Product, on_delete=models.CASCADE, primary_key=True)
    featured_image = models.ImageField(upload_to='images/featured/',
                                       null=True,
                                       blank=True,
                                       help_text="Product Featured Image (show in most places (200 x 200)px ).")
    
    image1 = models.ImageField(upload_to='images/products/', null=True, blank=True, help_text="Product Gallery Images")
    
    image2 = models.ImageField(upload_to='images/products/', null=True, blank=True, help_text="Product Gallery Images")
    
    image3 = models.ImageField(upload_to='images/products/', null=True, blank=True, help_text="Product Gallery Images")

    
    def __str__(self):
        return str(self.product_id.name)



class Stock(models.Model):
    product_id = models.OneToOneField(Product, on_delete=models.CASCADE, primary_key=True)
    stock = models.IntegerField()
    last_update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.product_id)




class Price(models.Model):
    product_id = models.OneToOneField(Product, on_delete=models.CASCADE, primary_key=True)
    low_price = models.DecimalField('Lowest Price', decimal_places=2, max_digits=9)
    normal_price = models.DecimalField('Normal Price', decimal_places=2, max_digits=9)
    base_price = models.DecimalField(decimal_places=2, max_digits=8)
    tenth_price = models.DecimalField('10x Price', decimal_places=2, max_digits=8)
    last_update_time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.product_id)

products/views.py
from django.shortcuts import render, get_object_or_404
from siteinfo.models import SiteSettings

# Create your views here.
def index(request):
    general_info = get_object_or_404(SiteSettings, pk=1)
    context = {
        'site_info': general_info,
    }
    return render(request, 'products/index.html', context)

products/templates/products/all_product_list.html
{% extends 'dashboard/admin-dash/main.html' %}

{% block content %}


<div class="mt-3 ml-2 mr-2 mb-5">
  <strong class="text-monospace " style="font-size:18px;" > <u>Products Panel</u> </strong>
  <a href="{% url 'dashboard:product_item_create' %}" class="d-inline-flex align-items-center btn btn-md btn-light float-right "> <i data-feather="user-plus"></i> &nbsp;New Item </a>
  
</div>

<table class="table table-hover table-md " id="table"
  data-url="json/data1.json"
  data-filter-control="true"
  data-show-search-clear-button="true">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col" data-filter-control="input">Model</th>
      <th scope="col">Stock</th>
      <th scope="col">Price</th>
      <th scope="col">Images</th>
      <th scope="col"> Edit </th>
    </tr>
  </thead>
  <tbody>
    {% for product in products %}
    <tr >
      <th scope="row">{{forloop.counter}}</th>
      <td><a href="{{product.get_absolute_url}}">{{product.name}}</a></td>
      <td>
	<strong class="{% if product.stock.stock < 10 %}  text-warning {% else %} text-success {% endif %} "> {{product.stock.stock}} </strong>
			      
      </td>
      <td>
	$ {{product.price.normal_price}}
      </td>
      <td>
	<img src="{{ product.productimages.featured_image.url }}" width="20px" height=auto>
      </td>
      <td><a href="{{product.id}}"> <i data-feather="edit"></i> </a> </td>
    </tr>
    
    {% endfor %}

  </tbody>
  </table>
    
{% endblock %}

products/templates/products/index.html
{% extends 'main.html' %}

{% block content %}

<h3> Hello Products </h3>


{% endblock %}

products/templates/products/price_form.html
{% extends 'dashboard/admin-dash/main.html' %}

{% block content %}
<div class="row justify-content-md-center">
  <div class="col-auto">
    <form action="" method="post" >
      {% csrf_token %}
      {{form.as_p}}
      <input type="submit" class="btn btn-success btn-md" value="Next >>">
    </form>
  </div>
</div>


{% endblock %}

products/templates/products/product_detail.html
{% extends 'dashboard/admin-dash/main.html' %}

{% block title %}
<title> Product Detail </title>
<link rel="stylesheet" href="https://unpkg.com/swiper/css/swiper.css">
<link rel="stylesheet" href="https://unpkg.com/swiper/css/swiper.min.css">

{% endblock %}


{% block content %}

<div class="row mt-5">

  <div class="col-12 col-sm-6">
    
    <!-- Swiper -->
    <a href="{% url 'dashboard:product_images_update' product.id%}" > <i data-feather="edit"></i>  Edit </a>
    <div class="main-swiper-wrap">
    <div class="swiper-container gallery-top">
      <div class="swiper-wrapper">
        <!-- Slides -->
	{% if product.productimages.featured_image %}
	<div class="swiper-slide text-center" style="background-image:url({{product.productimages.featured_image.url}});"> <span class="align-bottom text-warning">Featured</span> </div>
	{% endif %}
	
	{% if product.productimages.image1 %}
	<div class="swiper-slide text-center" style="background-image:url({{product.productimages.image1.url}});"> <span class="align-bottom text-warning">Image 1</span></div>
	{% endif %}
	
	{% if product.productimages.image2 %}
	<div class="swiper-slide text-center" style="background-image:url({{product.productimages.image2.url}});"><span class="align-bottom text-warning">Image 2</span></div>
	{% endif %}
	
	{% if product.productimages.image3 %}
	<div class="swiper-slide text-center" style="background-image:url({{product.productimages.image3.url}});"><span class="align-bottom text-warning">Image 3</span></div>
	{% endif %}
      </div>
      <!-- Add Arrows -->
      <div class="swiper-button-next swiper-button-black"></div>
      <div class="swiper-button-prev swiper-button-black"></div>
    </div>
    <div class="swiper-container gallery-thumbs">
      <div class="swiper-wrapper">
        <!-- Slides -->
	{% if product.productimages.featured_image %}
	<div class="swiper-slide" style="background-image:url({{product.productimages.featured_image.url}});"></div>
	{% endif %}
	
	{% if product.productimages.image1 %}
	<div class="swiper-slide" style="background-image:url({{product.productimages.image1.url}});"></div>
	{% endif %}
	
	{% if product.productimages.image2 %}
	<div class="swiper-slide" style="background-image:url({{product.productimages.image2.url}});"></div>
	{% endif %}
	
	{% if product.productimages.image3 %}
	<div class="swiper-slide" style="background-image:url({{product.productimages.image3.url}});"></div>
 	{% endif %}
      </div>
    </div>
    </div>
    
    
  </div>

  <div class="col-12 col-sm-6">
    <h5> Summary  <a href="{% url 'dashboard:product_item_update' product.id%}" class="ml-3" > <i data-feather="edit"></i>  Edit </a></h5>
    <table class="table table-sm mb-5">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Detail</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td> Name </td>
      <td> {{product.name}} </td>
    </tr>

    <tr>
      <td> Model </td>
      <td> {{product.model_number}} </td>
    </tr>

    
    <tr>
      <td> Dimension </td>
      <td> {{product.dimension}} </td>
    </tr>

    <tr>
      <td> Summary </td>
      <td> {{product.summary}} </td>
    </tr>


    <tr>
      <td> Basic Unit</td>
      <td> {{product.basic_unit}} </td>
    </tr>

    <tr>
      <td> Category </td>
      <td> <p> {% for main_cat in product.category1.all %} {{main_cat}}, {% endfor %} </p> <p> {% for sub_cat in product.category2.all %} {{sub_cat}},{% endfor %} </td>
    </tr>
    <tr>
      <td> Limited </td>
      <td> {{product.limited}} </td>
    </tr>

    <tr>
      <td> Can Sale </td>
      <td> {{product.active_for_sale}} </td>
    </tr>

    <tr>
      <td> Warehouse </td>
      <td> {{product.warehouse}} </td>
    </tr>

    
    <tr>
      <td> ID </td>
      <td> {{product.id}} </td>
    </tr>
    
    
  </tbody>
    </table>
    

    <h5> Stock  <a href="{% url 'dashboard:product_stock_update' product.id%}" class="ml-5"> <i data-feather="edit"></i>  Edit </a></h5>
    <table class="table table-sm mb-5">
  <tbody>
    <tr>
      <td>Stock </td>
      <td> {{ product.stock.stock }}</td>
    </tr>

    <tr>
      <td> Last Update </td>
      <td> {{product.stock.last_update}} </td>
    </tr>

    
  </tbody>
    </table>
    

    
    <h5> Prices <a href="{% url 'dashboard:product_price_update' product.id%}" class="ml-5"> <i data-feather="edit"></i>  Edit </a> </h5>
    <table class="table table-sm mb-5">
  <tbody>
    <tr>
      <td>Normal  </td>
      <td> {{ product.price.normal_price }}</td>
    </tr>

    <tr>
      <td> Lowest </td>
      <td> {{product.price.low_price}} </td>
    </tr>


    
    <tr>
      <td> 10x Price </td>
      <td> {{product.price.tenth_price}} </td>
    </tr>

    
    <tr>
      <td> Base </td>
      <td> {{product.price.base_price}} </td>
    </tr>

    
    <tr>
      <td> Last Update </td>
      <td> {{product.price.last_update_time}} </td>
    </tr>
    
    
    
    
  </tbody>
    </table>
    

  
    
  </div>
  

</div>



{% endblock %}


{% block footer %}
<script src="https://unpkg.com/swiper/js/swiper.js"></script>
<script src="https://unpkg.com/swiper/js/swiper.min.js"></script>
  <!-- Initialize Swiper -->
  <script>
    var galleryThumbs = new Swiper('.gallery-thumbs', {
      spaceBetween: 10,
      slidesPerView: 4,
      freeMode: true,
      loopedSlides: 5, //looped slides should be the same
      watchSlidesVisibility: true,
      watchSlidesProgress: true,
    });
    var galleryTop = new Swiper('.gallery-top', {
      spaceBetween: 10,
      loop: true,
      loopedSlides: 5, //looped slides should be the same
      navigation: {
        nextEl: '.swiper-button-next',
        prevEl: '.swiper-button-prev',
      },
      thumbs: {
        swiper: galleryThumbs,
      },
    });
  </script>


    <!-- Demo styles -->
  <style>
    .swiper-container {
      width: 100%;
      height: auto;
      margin-left: auto;
      margin-right: auto;
    }

    .swiper-slide {
      background-size: contain;
    background-position: center;
    background-repeat: no-repeat;
    height: 450px;
    widht: auto;
    }

    .gallery-top {
      height: 100%;
      width: 100%;
    }

    .gallery-thumbs {
      height: 50px;
      box-sizing: border-box;
      padding: 5px 0;
    }

    .gallery-thumbs .swiper-slide {
      height: 100%;
      opacity: 0.4;
    }

    .gallery-thumbs .swiper-slide-thumb-active {
      opacity: 1;
    }
  </style>
  
{% endblock %}

products/templates/products/product_form.html
{% extends 'dashboard/admin-dash/main.html' %}

{% block content %}
<div class="row justify-content-md-center">
  <div class="col-auto">
    <form action="" method="post" >
      {% csrf_token %}
      {{form.as_p}}
      <input type="submit" class="btn btn-success btn-md" value="Next >>">
    </form>
  </div>
</div>


{% endblock %}

products/templates/products/productimages_form.html
{% extends 'dashboard/admin-dash/main.html' %}

{% block content %}
<div class="row justify-content-md-center">
  <div class="col-auto">
    <form action="" method="post" enctype="multipart/form-data" >
      {% csrf_token %}
      {{form.as_p}}
      <input type="submit" class="btn btn-success btn-md" value="Next >>">
    </form>
  </div>
</div>


{% endblock %}

products/templates/products/stock_form.html
{% extends 'dashboard/admin-dash/main.html' %}

{% block content %}
<div class="row justify-content-md-center">
  <div class="col-auto">
    <form action="" method="post" >
      {% csrf_token %}
      {{form.as_p}}
      <input type="submit" class="btn btn-success btn-md" value="Next >>">
    </form>
  </div>
</div>


{% endblock %}